kind: Role
apiVersion: dockertest-dns-6bb34bf9.hcp.koreacentral.azmk8s.io/v1
metadata:
  namespace: xyz
  name: azure-devops-deploy-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: dockertest-dns-6bb34bf9.hcp.koreacentral.azmk8s.io/v1
metadata:
  name: azure-devops-deploy-manager
  namespace: xyz
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: dockertest-dns-6bb34bf9.hcp.koreacentral.azmk8s.io
roleRef:
  kind: Role
  name: azure-devops-deploy-role
  apiGroup: dockertest-dns-6bb34bf9.hcp.koreacentral.azmk8s.io
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockertestjmjm
  labels:
    app: docker-test
spec:
  selector:
    matchLabels:
      app: docker-test
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
      - name: dockertestjmjm
        image: dockertestjmjm.azurecr.io/docker-test:631
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: nodejs-port
